import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const yekanBakh = localFont({
  src: "../../public/fonts/Yekan-Bakh-FaNum-04-Regular.woff",
  variable: "--font-yekan-bakh",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${yekanBakh.variable} container`}>
        <main className="bg-container rounded-t-3xl flex flex-col items-center mt-6">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
